name: e-commerce

services:
  db:
    image: postgres:17.3-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
